global:
  resolve_timeout: 5m

route:
  receiver: default

  group_by: ["alertname", "project"]

  group_wait: 30s

  group_interval: 5m

  repeat_interval: 12h

  routes:
    - matchers:
        - severity = "critical"
      receiver: critical
      group_wait: 5s
      repeat_interval: 1h
      continue: false

    - matchers:
        - category = "pipeline"
      receiver: pipeline
      repeat_interval: 6h

inhibit_rules:
  - source_matchers:
      - alertname = "SecurityScanFailed"
    target_matchers:
      - category = "vulnerability"
    equal: ["project"]

  - source_matchers:
      - alertname = "PushgatewayDown"
    target_matchers:
      - category = "vulnerability"

  - source_matchers:
      - severity = "critical"
    target_matchers:
      - severity = "warning"
    equal: ["project", "alertname"]

receivers:
  - name: default
    webhook_configs:
      - url: "http://alert-sink:5001/webhook"
        send_resolved: true

  - name: critical
    webhook_configs:
      - url: "http://alert-sink:5001/webhook"
        send_resolved: true
    # slack_configs:
    #   - api_url_file: /etc/alertmanager/secrets/slack_webhook_url
    #     channel: "#security-alerts"
    #     title: "{{ .CommonAnnotations.summary }}"
    #     text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
    #     send_resolved: true
    #

  - name: pipeline
    webhook_configs:
      - url: "http://alert-sink:5001/webhook"
        send_resolved: true
