global:
  scrape_interval: 15s

  evaluation_interval: 15s

  external_labels:
    monitor: secmetrics
    environment: local

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          component: monitoring

  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          component: monitoring

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
        labels:
          component: security

  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]
        labels:
          component: monitoring
